### ISSUE TITLE
Tracking changes to the XMLHttpRequest spec

### ISSUE THREAD

**Issue by berniegp** [berniegp/mock-xmlhttprequest#4]
The XMLHttpRequest spec has evolved since this library was created. This issue tracks what needs to be added or modified to implement the changes to the spec since the "24 October 2016" version.

[Spec](https://xhr.spec.whatwg.org/)
[Github spec repo](https://github.com/whatwg/xhr)

- [x] [Reset response for abort() during DONE](https://github.com/whatwg/xhr/commit/daecfff02e0a95776f305097a752148071d58d07)
- [x] [Clarify when subsubsubsteps run in "process response" ](https://github.com/whatwg/xhr/commit/95dd85b366ea59e3e45a85b44418a5bade64f084)
- [x] [Regression fix: need transmitted/length defined before progress event dispatch](https://github.com/whatwg/xhr/commit/f45453e0e1aedc746f9fa906c54f7d29c8207d9d)
- [x] [Editorial: use a single response object ](https://github.com/whatwg/xhr/commit/d618835af5562e015f7ac10f3fe5e0ce5925ed13)
- [x] [Account for loadstart being able to change state ](https://github.com/whatwg/xhr/commit/2720b395f104bd75ed100e8a4362aea81c40cade)
- [x] [Align header handling with Fetch](https://github.com/whatwg/xhr/commit/a6e79810a381b8e336570da797967c4b34e0c6b1)
- [x] [Align with Fetch's upcoming abort revamp ](https://github.com/whatwg/xhr/commit/1a8f6910dfc1bf4edc46b23076380cf4cedeaca0)
- [x] [Use the API URL character encoding for XMLHttpRequest ](https://github.com/whatwg/xhr/commit/6f14c60f5ae81381c12ff50f5f6898a1583b570d)

**Comment by berniegp** [comment]
whatwg/xhr@daecfff02e0a95776f305097a752148071d58d07

**Comment by berniegp** [comment]
whatwg/xhr#130
whatwg/xhr#101
